### ISSUE TITLE
[BUG] Traceback Error when processing (Default posters load in the Poster Manager)

### ISSUE THREAD

**Issue by mels0n** [jackkerouac/aphrodite#31]
**Describe the bug**
Run Now of Schedule Fails

**To Reproduce**
1. Setup Jellyfin
2. Setup a Schedule
3. Click Run Now (Note: Logs show the same as below for a scheduled event firing normally)
4. Screen refreshes with no indication of a process running
5. Poster Manager continues to have default images

![Image](https://github.com/user-attachments/assets/2e7d4f1d-9a00-4f58-a702-d607e30e4fa1)

**Expected behavior**
Images to be badged.

**Version (please complete the following information):**
 - Version GUI Shows v2.2.5

Docker Image Matches the sha for latest/3.0.0 
```
sha256:68c34065e53266f5cff6283ca28d646e6c3119cf268e98cf819bdc9765abab14
```
```
ghcr.io/jackkerouac/aphrodite             <none>    sha256:68c34065e53266f5cff6283ca28d646e6c3119cf268e98cf819bdc9765abab14   725322d34d10   19 hours ago    923MB
```
**Additional context**

Running a Test Connection for Jellyfin
```
[2025-06-06 18:52:46,195] INFO in check: Received data for API connection check: {'url': 'http://jellyfin:8096', 'api_key': '<API KEY>', 'user_id': '<USER ID>'}
2025-06-06 18:52:46,195 - app.api.check - INFO - Received data for API connection check: {'url': 'http://jellyfin:8096', 'api_key': '<API KEY>', 'user_id': '<USER ID>'}
2025-06-06 18:52:46,195 - app.api.check - INFO - Received data for API connection check: {'url': 'http://jellyfin:8096', 'api_key': '<API KEY>', 'user_id': '<USER ID>'}
2025-06-06 18:52:46,205 - werkzeug - INFO - 10.0.15.8 - - [06/Jun/2025 18:52:46] "POST /api/check/ HTTP/1.1" 200 -
```
Triggering a schedule via Run Now
```
2025-06-06 18:53:56,843 - werkzeug - INFO - 10.0.15.8 - - [06/Jun/2025 18:53:56] "GET /api/changes/ HTTP/1.1" 200 -
[2025-06-06 18:53:58,933] DEBUG in settings_service: DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-06 18:53:58,933 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-06 18:53:58,933 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-06 18:53:58,937 - werkzeug - INFO - 10.0.15.8 - - [06/Jun/2025 18:53:58] "GET /api/schedules/status HTTP/1.1" 200 -
[2025-06-06 18:53:58,937] DEBUG in settings_service: DEBUG: Database connection successful
2025-06-06 18:53:58,937 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
2025-06-06 18:53:58,937 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
2025-06-06 18:53:58,959 - werkzeug - INFO - 10.0.15.8 - - [06/Jun/2025 18:53:58] "GET /api/schedules/ HTTP/1.1" 200 -
[2025-06-06 18:54:03,073] INFO in scheduler_service: Manually triggered schedule '8d988d4b-45ab-4104-b585-73608b7f8c16'
2025-06-06 18:54:03,073 - app.services.scheduler_service - INFO - Manually triggered schedule '8d988d4b-45ab-4104-b585-73608b7f8c16'
2025-06-06 18:54:03,073 - app.services.scheduler_service - INFO - Manually triggered schedule '8d988d4b-45ab-4104-b585-73608b7f8c16'
2025-06-06 18:54:03,074 - werkzeug - INFO - 10.0.15.8 - - [06/Jun/2025 18:54:03] "POST /api/schedules/8d988d4b-45ab-4104-b585-73608b7f8c16/run HTTP/1.1" 200 -
2025-06-06 18:54:03,076 - apscheduler.executors.default - INFO - Running job "4k test (trigger: cron[month='*', day='*', day_of_week='*', hour='*', minute='0'], next run at: 2025-06-06 19:00:00 UTC)" (scheduled at 2025-06-06 18:54:03.073435+00:00)
[2025-06-06 18:54:03,077] INFO in scheduler_service: Starting scheduled job '8d988d4b-45ab-4104-b585-73608b7f8c16'
2025-06-06 18:54:03,077 - app.services.scheduler_service - INFO - Starting scheduled job '8d988d4b-45ab-4104-b585-73608b7f8c16'
2025-06-06 18:54:03,077 - app.services.scheduler_service - INFO - Starting scheduled job '8d988d4b-45ab-4104-b585-73608b7f8c16'
[2025-06-06 18:54:03,077] DEBUG in settings_service: DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-06 18:54:03,077 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-06 18:54:03,077 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
[2025-06-06 18:54:03,079] DEBUG in settings_service: DEBUG: Database connection successful
2025-06-06 18:54:03,079 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
2025-06-06 18:54:03,079 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
[2025-06-06 18:54:03,083] DEBUG in settings_service: DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-06 18:54:03,083 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-06 18:54:03,083 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-06 18:54:03,086 - werkzeug - INFO - 10.0.15.8 - - [06/Jun/2025 18:54:03] "GET /api/schedules/status HTTP/1.1" 200 -
[2025-06-06 18:54:03,086] DEBUG in settings_service: DEBUG: Database connection successful
2025-06-06 18:54:03,086 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
2025-06-06 18:54:03,086 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
2025-06-06 18:54:03,102 - werkzeug - INFO - 10.0.15.8 - - [06/Jun/2025 18:54:03] "GET /api/schedules/ HTTP/1.1" 200 -
Starting workflow 2d343c6b-7e12-4dd8-b3e6-c88e53147795 of type library_batch
Processing library all in workflow 2d343c6b-7e12-4dd8-b3e6-c88e53147795
Processing library all for workflow 2d343c6b-7e12-4dd8-b3e6-c88e53147795
[2025-06-06 18:54:04,119] DEBUG in settings_service: DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-06 18:54:04,119 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-06 18:54:04,119 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
[2025-06-06 18:54:04,119] DEBUG in settings_service: DEBUG: Database connection successful
2025-06-06 18:54:04,119 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
2025-06-06 18:54:04,119 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
Using script at: /app/aphrodite.py
Executing command: python /app/aphrodite.py library all --retries 3 --skip-processed
[2025-06-06 18:54:04,130] INFO in scheduler_service: Created workflow 2d343c6b-7e12-4dd8-b3e6-c88e53147795 for scheduled job '8d988d4b-45ab-4104-b585-73608b7f8c16'
2025-06-06 18:54:04,130 - app.services.scheduler_service - INFO - Created workflow 2d343c6b-7e12-4dd8-b3e6-c88e53147795 for scheduled job '8d988d4b-45ab-4104-b585-73608b7f8c16'
2025-06-06 18:54:04,130 - app.services.scheduler_service - INFO - Created workflow 2d343c6b-7e12-4dd8-b3e6-c88e53147795 for scheduled job '8d988d4b-45ab-4104-b585-73608b7f8c16'
Command completed with return code: 1
Error output: 2025-06-06 18:54:04,678 - aphrodite_helpers.settings_compat - INFO - load_settings called with path: settings.yaml
2025-06-06 18:54:04,678 - aphrodite_helpers.settings_compat - INFO - Attempting to load settings from database...
2025-06-06 18:54:04,683 - app.services.settings_service - INFO - DEBUG: Current database version: 1
2025-06-06 18:54:04,683 - aphrodite_helpers.settings_compat - INFO - Database version: 1
2025-06-06 18:54:04,683 - aphrodite_helpers.settings_compat - INFO - Loading settings from SQLite database
2025-06-06 18:54:04,704 - aphrodite_helpers.settings_compat - INFO - Successfully loaded settings from database
2025-06-06 18:54:04,704 - aphrodite_helpers.settings_compat - INFO - load_settings called with path: settings.yaml
2025-06-06 18:54:04,704 - aphrodite_helpers.settings_compat - INFO - Attempting to load settings from database...
2025-06-06 18:54:04,708 - app.services.settings_service - INFO - DEBUG: Current database version: 1
2025-06-06 18:54:04,708 - aphrodite_helpers.settings_compat - INFO - Database version: 1
2025-06-06 18:54:04,708 - aphrodite_helpers.settings_compat - INFO - Loading settings from SQLite database
2025-06-06 18:54:04,708 - aphrodite_helpers.settings_compat - INFO - Successfully loaded settings from database
Traceback (most recent call last):
  File "/app/aphrodite.py", line 582, in <module>
    sys.exit(main())
  File "/app/aphrodite.py", line 567, in main
    process_library_items(
  File "/app/aphrodite.py", line 323, in process_library_items
    items = get_library_items(jellyfin_url, api_key, user_id, library_id)
  File "/app/aphrodite_helpers/check_jellyfin_connection.py", line 91, in get_library_items
    count_resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://jellyfin:8096/Users/<USER ID>/Items?ParentId=all&StartIndex=0&Limit=1&Recursive=true
Library all processing completed: success=False
Workflow 2d343c6b-7e12-4dd8-b3e6-c88e53147795 completed with overall success: False
Checking for next workflow after completing 2d343c6b-7e12-4dd8-b3e6-c88e53147795
```

**Comment by mels0n** [comment]
![Image](https://github.com/user-attachments/assets/6b4b502a-0a1d-4157-96dc-e49f6259488b)

I believe this is because the call it is making is library=all and it might be doing that, because no matter what I select, when I update the schedule it is blank when I edit the schedule.

Also the Update Schedule button only becomes active when I change the cron - IE. if I select a new library it doesn't become available.

**Comment by jackkerouac** [comment]
This has been fixed in v3.0.0. I think you noticed it the same time I did!

Also, that guy is super handsome!

**Comment by mels0n** [comment]
> This has been fixed in v3.0.0. I think you noticed it the same time I did!
> 
> Also, that guy is super handsome!

How does one get 3.0.0?

**Comment by mels0n** [comment]
@jackkerouac - I just tested this in 3.1.1 with a completely new setup docker setup and it doesn't appear anything has changed for the experiences reported. Shall I publish the issues separately in a new reports for clarity? 

- Default posters still load in the Poster Manager.
- Schedule doesn't save library location.
- Traceback error still exists calling 'library=all'

**Comment by louanrobert** [comment]
Hi !

I can confirm there is an issue with the schedule ; libraries selection is not saved.
@jackkerouac you should probably reopen this issue.

**Comment by jackkerouac** [comment]
I will re-open this and look into it further.

**Comment by mels0n** [comment]
> * Schedule doesn't save library location.
> * Traceback error still exists calling 'library=all'



> [@jackkerouac](https://github.com/jackkerouac) - I just tested this in 3.1.1 with a completely new setup docker setup and it doesn't appear anything has changed for the experiences reported. Shall I publish the issues separately in a new reports for clarity?
> 
> * Default posters still load in the Poster Manager.
> * Schedule doesn't save library location.
> * Traceback error still exists calling 'library=all'

3.5 fixes these issues for me.
```
Schedule doesn't save library location.
Traceback error still exists calling 'library=all'
```
This one still appears to exist in 3.5 - fresh install
```
Default posters load in the Poster Manager.
```

**Comment by jackkerouac** [comment]
Can you explain to me what you mean by default posters? Are you saying that only the default pictures of the image above (the guy with the vacation shirt) are appearing instead of your Jellyfin posters (as they appear on Jellyfin)?

And just to be sure, the poster ARE present in Jellyfin?

**Comment by mels0n** [comment]
Yes exactly the guy with vacation shirt is the only image ever displayed. My current setup was a completely fresh docker in 3.5, but this has been the experience since 3.0.0 (which was my first install.)

Aphrodite before badging:

![Image](https://github.com/user-attachments/assets/6e3d6318-3b53-4301-bb4f-380ff00a5c58)

Aphrodite post badging:

![Image](https://github.com/user-attachments/assets/501168b8-3acc-40b6-a7e8-2ec50b18bda4)

Jellyfin post badging:

![Image](https://github.com/user-attachments/assets/db79fbe9-6878-4cc0-b4cf-1df7b393c275)

**Comment by jackkerouac** [comment]
That's a little ... odd. Can you go into the Poster Manager and post the logs of what happens when you choose a library?  Thanks!

**Comment by mels0n** [comment]
The logs below are of me doing the following steps.

1. Open the WebGUI
2. Click Poster Manager
3. Select the badged library from the above Jellyfin screenshot.

```
[2025-06-09 13:47:24,510] INFO in __init__: Serving frontend route: ''
2025-06-09 13:47:24,510 - app - INFO - Serving frontend route: ''
2025-06-09 13:47:24,510 - app - INFO - Serving frontend route: ''
[2025-06-09 13:47:24,511] INFO in __init__: Static folder: /app/aphrodite-web/frontend/dist
2025-06-09 13:47:24,511 - app - INFO - Static folder: /app/aphrodite-web/frontend/dist
2025-06-09 13:47:24,511 - app - INFO - Static folder: /app/aphrodite-web/frontend/dist
[2025-06-09 13:47:24,511] INFO in __init__: Static folder exists: True
2025-06-09 13:47:24,511 - app - INFO - Static folder exists: True
2025-06-09 13:47:24,511 - app - INFO - Static folder exists: True
[2025-06-09 13:47:24,511] INFO in __init__: Serving SPA route: ''
2025-06-09 13:47:24,511 - app - INFO - Serving SPA route: ''
2025-06-09 13:47:24,511 - app - INFO - Serving SPA route: ''
[2025-06-09 13:47:24,511] INFO in __init__: DEBUG: Original host: aphrodite.<reverse proxy hostname>
2025-06-09 13:47:24,511 - app - INFO - DEBUG: Original host: aphrodite.<reverse proxy hostname>
2025-06-09 13:47:24,511 - app - INFO - DEBUG: Original host: aphrodite.<reverse proxy hostname>
[2025-06-09 13:47:24,511] INFO in __init__: DEBUG: Docker host: aphrodite.<reverse proxy hostname>, port: 443
2025-06-09 13:47:24,511 - app - INFO - DEBUG: Docker host: aphrodite.<reverse proxy hostname>, port: 443
2025-06-09 13:47:24,511 - app - INFO - DEBUG: Docker host: aphrodite.<reverse proxy hostname>, port: 443
[2025-06-09 13:47:24,512] INFO in __init__: DEBUG: Using host: aphrodite.<reverse proxy hostname>:443
2025-06-09 13:47:24,512 - app - INFO - DEBUG: Using host: aphrodite.<reverse proxy hostname>:443
2025-06-09 13:47:24,512 - app - INFO - DEBUG: Using host: aphrodite.<reverse proxy hostname>:443
[2025-06-09 13:47:24,512] INFO in __init__: DEBUG: Injecting base URL: https://aphrodite.<reverse proxy hostname>:443
2025-06-09 13:47:24,512 - app - INFO - DEBUG: Injecting base URL: https://aphrodite.<reverse proxy hostname>:443
2025-06-09 13:47:24,512 - app - INFO - DEBUG: Injecting base URL: https://aphrodite.<reverse proxy hostname>:443
2025-06-09 13:47:24,512 - werkzeug - INFO - 10.0.15.8 - - [09/Jun/2025 13:47:24] "GET / HTTP/1.1" 200 -
[2025-06-09 13:47:24,552] INFO in __init__: Serving frontend route: 'js/chunk-vendors.a21f50f1.js'
2025-06-09 13:47:24,552 - app - INFO - Serving frontend route: 'js/chunk-vendors.a21f50f1.js'
2025-06-09 13:47:24,552 - app - INFO - Serving frontend route: 'js/chunk-vendors.a21f50f1.js'
[2025-06-09 13:47:24,552] INFO in __init__: Static folder: /app/aphrodite-web/frontend/dist
2025-06-09 13:47:24,552 - app - INFO - Static folder: /app/aphrodite-web/frontend/dist
2025-06-09 13:47:24,552 - app - INFO - Static folder: /app/aphrodite-web/frontend/dist
[2025-06-09 13:47:24,553] INFO in __init__: Static folder exists: True
2025-06-09 13:47:24,553 - app - INFO - Static folder exists: True
[2025-06-09 13:47:24,554] INFO in __init__: Serving frontend route: 'js/app.de4e3832.js'
2025-06-09 13:47:24,553 - app - INFO - Static folder exists: True
2025-06-09 13:47:24,554 - app - INFO - Serving frontend route: 'js/app.de4e3832.js'
2025-06-09 13:47:24,554 - app - INFO - Serving frontend route: 'js/app.de4e3832.js'
[2025-06-09 13:47:24,555] INFO in __init__: Serving frontend route: 'css/app.caa320ea.css'
2025-06-09 13:47:24,555 - app - INFO - Serving frontend route: 'css/app.caa320ea.css'
[2025-06-09 13:47:24,555] INFO in __init__: Serving static file: js/chunk-vendors.a21f50f1.js
2025-06-09 13:47:24,555 - app - INFO - Serving frontend route: 'css/app.caa320ea.css'
2025-06-09 13:47:24,555 - app - INFO - Serving static file: js/chunk-vendors.a21f50f1.js
2025-06-09 13:47:24,555 - app - INFO - Serving static file: js/chunk-vendors.a21f50f1.js
[2025-06-09 13:47:24,555] INFO in __init__: Static folder: /app/aphrodite-web/frontend/dist
2025-06-09 13:47:24,555 - app - INFO - Static folder: /app/aphrodite-web/frontend/dist
2025-06-09 13:47:24,558 - werkzeug - INFO - 10.0.15.8 - - [09/Jun/2025 13:47:24] "GET /js/chunk-vendors.a21f50f1.js HTTP/1.1" 304 -
2025-06-09 13:47:24,555 - app - INFO - Static folder: /app/aphrodite-web/frontend/dist
[2025-06-09 13:47:24,556] INFO in __init__: Static folder: /app/aphrodite-web/frontend/dist
2025-06-09 13:47:24,556 - app - INFO - Static folder: /app/aphrodite-web/frontend/dist
2025-06-09 13:47:24,556 - app - INFO - Static folder: /app/aphrodite-web/frontend/dist
[2025-06-09 13:47:24,559] INFO in __init__: Static folder exists: True
2025-06-09 13:47:24,559 - app - INFO - Static folder exists: True
2025-06-09 13:47:24,559 - app - INFO - Static folder exists: True
[2025-06-09 13:47:24,560] INFO in __init__: Static folder exists: True
2025-06-09 13:47:24,560 - app - INFO - Static folder exists: True
2025-06-09 13:47:24,560 - app - INFO - Static folder exists: True
[2025-06-09 13:47:24,560] INFO in __init__: Serving static file: js/app.de4e3832.js
2025-06-09 13:47:24,560 - app - INFO - Serving static file: js/app.de4e3832.js
[2025-06-09 13:47:24,560] INFO in __init__: Serving static file: css/app.caa320ea.css
2025-06-09 13:47:24,560 - app - INFO - Serving static file: css/app.caa320ea.css
2025-06-09 13:47:24,560 - app - INFO - Serving static file: css/app.caa320ea.css
2025-06-09 13:47:24,560 - app - INFO - Serving static file: js/app.de4e3832.js
2025-06-09 13:47:24,561 - werkzeug - INFO - 10.0.15.8 - - [09/Jun/2025 13:47:24] "GET /css/app.caa320ea.css HTTP/1.1" 304 -
2025-06-09 13:47:24,562 - werkzeug - INFO - 10.0.15.8 - - [09/Jun/2025 13:47:24] "GET /js/app.de4e3832.js HTTP/1.1" 304 -
[2025-06-09 13:47:24,640] INFO in settings_service: DEBUG: Initializing database at /app/data/aphrodite.db
2025-06-09 13:47:24,640 - app.services.settings_service - INFO - DEBUG: Initializing database at /app/data/aphrodite.db
2025-06-09 13:47:24,640 - app.services.settings_service - INFO - DEBUG: Initializing database at /app/data/aphrodite.db
[2025-06-09 13:47:24,640] DEBUG in settings_service: DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-09 13:47:24,640 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-09 13:47:24,640 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
[2025-06-09 13:47:24,641] INFO in settings_service: DEBUG: Initializing database at /app/data/aphrodite.db
2025-06-09 13:47:24,641 - app.services.settings_service - INFO - DEBUG: Initializing database at /app/data/aphrodite.db
2025-06-09 13:47:24,641 - app.services.settings_service - INFO - DEBUG: Initializing database at /app/data/aphrodite.db
[2025-06-09 13:47:24,641] DEBUG in settings_service: DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-09 13:47:24,641 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
[2025-06-09 13:47:24,643] DEBUG in settings_service: DEBUG: Database connection successful
[2025-06-09 13:47:24,643] INFO in __init__: Looking for image android-chrome-192x192.png in /app/images
2025-06-09 13:47:24,641 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-09 13:47:24,643 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
2025-06-09 13:47:24,643 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
2025-06-09 13:47:24,643 - app - INFO - Looking for image android-chrome-192x192.png in /app/images
2025-06-09 13:47:24,643 - app - INFO - Looking for image android-chrome-192x192.png in /app/images
[2025-06-09 13:47:24,645] DEBUG in settings_service: DEBUG: Database connection successful
2025-06-09 13:47:24,645 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
[2025-06-09 13:47:24,645] INFO in __init__: Looking for image professor_relaxing.png in /app/images
2025-06-09 13:47:24,645 - app - INFO - Looking for image professor_relaxing.png in /app/images
2025-06-09 13:47:24,645 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
2025-06-09 13:47:24,645 - app - INFO - Looking for image professor_relaxing.png in /app/images
2025-06-09 13:47:24,647 - werkzeug - INFO - 10.0.15.8 - - [09/Jun/2025 13:47:24] "GET /images/professor_relaxing.png HTTP/1.1" 304 -
2025-06-09 13:47:24,647 - werkzeug - INFO - 10.0.15.8 - - [09/Jun/2025 13:47:24] "GET /images/android-chrome-192x192.png HTTP/1.1" 304 -
[2025-06-09 13:47:24,649] INFO in __init__: Looking for image github.webp in /app/images
2025-06-09 13:47:24,649 - app - INFO - Looking for image github.webp in /app/images
2025-06-09 13:47:24,649 - app - INFO - Looking for image github.webp in /app/images
[2025-06-09 13:47:24,651] INFO in __init__: Looking for image kofi.png in /app/images
2025-06-09 13:47:24,651 - app - INFO - Looking for image kofi.png in /app/images
2025-06-09 13:47:24,651 - app - INFO - Looking for image kofi.png in /app/images
[2025-06-09 13:47:24,652] INFO in settings_service: DEBUG: Created/verified settings table
2025-06-09 13:47:24,652 - app.services.settings_service - INFO - DEBUG: Created/verified settings table
[2025-06-09 13:47:24,653] INFO in settings_service: DEBUG: Created/verified settings table
2025-06-09 13:47:24,652 - app.services.settings_service - INFO - DEBUG: Created/verified settings table
2025-06-09 13:47:24,653 - app.services.settings_service - INFO - DEBUG: Created/verified settings table
2025-06-09 13:47:24,654 - werkzeug - INFO - 10.0.15.8 - - [09/Jun/2025 13:47:24] "GET /images/github.webp HTTP/1.1" 304 -
2025-06-09 13:47:24,653 - app.services.settings_service - INFO - DEBUG: Created/verified settings table
2025-06-09 13:47:24,655 - werkzeug - INFO - 10.0.15.8 - - [09/Jun/2025 13:47:24] "GET /images/kofi.png HTTP/1.1" 304 -
[2025-06-09 13:47:24,658] INFO in settings_service: DEBUG: Created/verified api_keys table
2025-06-09 13:47:24,658 - app.services.settings_service - INFO - DEBUG: Created/verified api_keys table
2025-06-09 13:47:24,658 - app.services.settings_service - INFO - DEBUG: Created/verified api_keys table
[2025-06-09 13:47:24,659] INFO in settings_service: DEBUG: Created/verified api_keys table
2025-06-09 13:47:24,659 - app.services.settings_service - INFO - DEBUG: Created/verified api_keys table
2025-06-09 13:47:24,659 - app.services.settings_service - INFO - DEBUG: Created/verified api_keys table
[2025-06-09 13:47:24,665] INFO in settings_service: DEBUG: Created/verified badge_settings table
2025-06-09 13:47:24,670 - werkzeug - INFO - 10.0.15.8 - - [09/Jun/2025 13:47:24] "GET /api/changes/ HTTP/1.1" 200 -
2025-06-09 13:47:24,665 - app.services.settings_service - INFO - DEBUG: Created/verified badge_settings table
[2025-06-09 13:47:24,670] INFO in settings_service: DEBUG: Created/verified badge_settings table
2025-06-09 13:47:24,670 - app.services.settings_service - INFO - DEBUG: Created/verified badge_settings table
2025-06-09 13:47:24,665 - app.services.settings_service - INFO - DEBUG: Created/verified badge_settings table
2025-06-09 13:47:24,670 - app.services.settings_service - INFO - DEBUG: Created/verified badge_settings table
[2025-06-09 13:47:24,673] INFO in settings_service: DEBUG: Created/verified settings_version table
2025-06-09 13:47:24,673 - werkzeug - INFO - 10.0.15.8 - - [09/Jun/2025 13:47:24] "GET /api/jobs/active-jobs-with-workflows HTTP/1.1" 404 -
2025-06-09 13:47:24,673 - app.services.settings_service - INFO - DEBUG: Created/verified settings_version table
2025-06-09 13:47:24,673 - app.services.settings_service - INFO - DEBUG: Created/verified settings_version table
[2025-06-09 13:47:24,676] INFO in settings_service: DEBUG: Created/verified app_version table
2025-06-09 13:47:24,676 - app.services.settings_service - INFO - DEBUG: Created/verified app_version table
2025-06-09 13:47:24,676 - app.services.settings_service - INFO - DEBUG: Created/verified app_version table
[2025-06-09 13:47:24,676] INFO in settings_service: DEBUG: Created/verified settings_version table
2025-06-09 13:47:24,676 - app.services.settings_service - INFO - DEBUG: Created/verified settings_version table
2025-06-09 13:47:24,676 - app.services.settings_service - INFO - DEBUG: Created/verified settings_version table
[2025-06-09 13:47:24,677] INFO in settings_service: DEBUG: Created/verified schedules table
2025-06-09 13:47:24,677 - app.services.settings_service - INFO - DEBUG: Created/verified schedules table
2025-06-09 13:47:24,677 - app.services.settings_service - INFO - DEBUG: Created/verified schedules table
[2025-06-09 13:47:24,677] INFO in settings_service: DEBUG: Created/verified app_version table
2025-06-09 13:47:24,677 - app.services.settings_service - INFO - DEBUG: Created/verified app_version table
2025-06-09 13:47:24,677 - app.services.settings_service - INFO - DEBUG: Created/verified app_version table
[2025-06-09 13:47:24,678] INFO in settings_service: DEBUG: Created/verified schedule_processing_options table
2025-06-09 13:47:24,678 - app.services.settings_service - INFO - DEBUG: Created/verified schedule_processing_options table
2025-06-09 13:47:24,678 - app.services.settings_service - INFO - DEBUG: Created/verified schedule_processing_options table
[2025-06-09 13:47:24,678] INFO in settings_service: DEBUG: Created/verified schedule_target_directories table
2025-06-09 13:47:24,678 - app.services.settings_service - INFO - DEBUG: Created/verified schedule_target_directories table
[2025-06-09 13:47:24,678] INFO in settings_service: DEBUG: Created/verified schedules table
2025-06-09 13:47:24,678 - app.services.settings_service - INFO - DEBUG: Created/verified schedule_target_directories table
2025-06-09 13:47:24,678 - app.services.settings_service - INFO - DEBUG: Created/verified schedules table
2025-06-09 13:47:24,678 - app.services.settings_service - INFO - DEBUG: Created/verified schedules table
[2025-06-09 13:47:24,680] INFO in settings_service: DEBUG: Created/verified job_history table
2025-06-09 13:47:24,680 - app.services.settings_service - INFO - DEBUG: Created/verified job_history table
2025-06-09 13:47:24,680 - app.services.settings_service - INFO - DEBUG: Created/verified job_history table
[2025-06-09 13:47:24,681] INFO in settings_service: DEBUG: Created/verified schedule_processing_options table
2025-06-09 13:47:24,681 - app.services.settings_service - INFO - DEBUG: Created/verified schedule_processing_options table
2025-06-09 13:47:24,681 - app.services.settings_service - INFO - DEBUG: Created/verified schedule_processing_options table
[2025-06-09 13:47:24,681] INFO in settings_service: DEBUG: Created/verified review_sources table
2025-06-09 13:47:24,681 - app.services.settings_service - INFO - DEBUG: Created/verified review_sources table
2025-06-09 13:47:24,681 - app.services.settings_service - INFO - DEBUG: Created/verified review_sources table
[2025-06-09 13:47:24,682] INFO in settings_service: DEBUG: Created/verified schedule_target_directories table
2025-06-09 13:47:24,682 - app.services.settings_service - INFO - DEBUG: Created/verified schedule_target_directories table
2025-06-09 13:47:24,682 - app.services.settings_service - INFO - DEBUG: Created/verified schedule_target_directories table
[2025-06-09 13:47:24,684] INFO in settings_service: DEBUG: Created/verified job_history table
2025-06-09 13:47:24,684 - app.services.settings_service - INFO - DEBUG: Created/verified job_history table
2025-06-09 13:47:24,684 - app.services.settings_service - INFO - DEBUG: Created/verified job_history table
[2025-06-09 13:47:24,684] INFO in settings_service: DEBUG: Created/verified review_settings table
2025-06-09 13:47:24,684 - app.services.settings_service - INFO - DEBUG: Created/verified review_settings table
2025-06-09 13:47:24,684 - app.services.settings_service - INFO - DEBUG: Created/verified review_settings table
[2025-06-09 13:47:24,685] INFO in settings_service: DEBUG: Created/verified review_sources table
2025-06-09 13:47:24,685 - app.services.settings_service - INFO - DEBUG: Created/verified review_sources table
2025-06-09 13:47:24,685 - app.services.settings_service - INFO - DEBUG: Created/verified review_sources table
[2025-06-09 13:47:24,685] INFO in settings_service: DEBUG: Database initialization completed successfully
2025-06-09 13:47:24,685 - app.services.settings_service - INFO - DEBUG: Database initialization completed successfully
[2025-06-09 13:47:24,686] INFO in settings_service: DEBUG: Created/verified review_settings table
2025-06-09 13:47:24,685 - app.services.settings_service - INFO - DEBUG: Database initialization completed successfully
2025-06-09 13:47:24,686 - app.services.settings_service - INFO - DEBUG: Created/verified review_settings table
[2025-06-09 13:47:24,690] DEBUG in settings_service: DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-09 13:47:24,686 - app.services.settings_service - INFO - DEBUG: Created/verified review_settings table
2025-06-09 13:47:24,690 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-09 13:47:24,690 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
[2025-06-09 13:47:24,691] INFO in settings_service: DEBUG: Database initialization completed successfully
2025-06-09 13:47:24,691 - app.services.settings_service - INFO - DEBUG: Database initialization completed successfully
2025-06-09 13:47:24,691 - app.services.settings_service - INFO - DEBUG: Database initialization completed successfully
[2025-06-09 13:47:24,691] DEBUG in settings_service: DEBUG: Database connection successful
2025-06-09 13:47:24,691 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
2025-06-09 13:47:24,691 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
[2025-06-09 13:47:24,692] DEBUG in settings_service: DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-09 13:47:24,692 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-09 13:47:24,692 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
[2025-06-09 13:47:24,692] DEBUG in settings_service: DEBUG: Database connection successful
2025-06-09 13:47:24,692 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
2025-06-09 13:47:24,692 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
[2025-06-09 13:47:24,695] INFO in settings_service: DEBUG: Current database version: 1
2025-06-09 13:47:24,695 - app.services.settings_service - INFO - DEBUG: Current database version: 1
2025-06-09 13:47:24,695 - app.services.settings_service - INFO - DEBUG: Current database version: 1
[2025-06-09 13:47:24,695] INFO in settings_migration: Migration status check: YAML exists: True, DB version: 1, Migration needed: False
2025-06-09 13:47:24,695 - app.api.settings_migration - INFO - Migration status check: YAML exists: True, DB version: 1, Migration needed: False
2025-06-09 13:47:24,695 - app.api.settings_migration - INFO - Migration status check: YAML exists: True, DB version: 1, Migration needed: False
2025-06-09 13:47:24,695 - werkzeug - INFO - 10.0.15.8 - - [09/Jun/2025 13:47:24] "GET /api/settings/migration/status HTTP/1.1" 200 -
[2025-06-09 13:47:24,696] INFO in version_service: VersionService initialized with base directory: /app
2025-06-09 13:47:24,696 - app.services.version_service - INFO - VersionService initialized with base directory: /app
2025-06-09 13:47:24,696 - app.services.version_service - INFO - VersionService initialized with base directory: /app
[2025-06-09 13:47:24,696] DEBUG in settings_service: DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-09 13:47:24,696 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-09 13:47:24,696 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
[2025-06-09 13:47:24,697] DEBUG in settings_service: DEBUG: Database connection successful
2025-06-09 13:47:24,697 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
2025-06-09 13:47:24,697 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
[2025-06-09 13:47:24,698] DEBUG in settings_service: DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-09 13:47:24,698 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-09 13:47:24,698 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
[2025-06-09 13:47:24,698] DEBUG in settings_service: DEBUG: Database connection successful
2025-06-09 13:47:24,698 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
2025-06-09 13:47:24,698 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
[2025-06-09 13:47:24,699] INFO in version_service: Using cached version data from database
2025-06-09 13:47:24,699 - app.services.version_service - INFO - Using cached version data from database
2025-06-09 13:47:24,699 - app.services.version_service - INFO - Using cached version data from database
2025-06-09 13:47:24,700 - werkzeug - INFO - 10.0.15.8 - - [09/Jun/2025 13:47:24] "GET /api/version/check?_cb=1749476844043 HTTP/1.1" 200 -
2025-06-09 13:47:24,707 - werkzeug - INFO - 10.0.15.8 - - [09/Jun/2025 13:47:24] "GET /api/database/stats HTTP/1.1" 200 -
[2025-06-09 13:47:26,543] INFO in __init__: Serving frontend route: 'css/226.c6b3ffe3.css'
2025-06-09 13:47:26,543 - app - INFO - Serving frontend route: 'css/226.c6b3ffe3.css'
2025-06-09 13:47:26,543 - app - INFO - Serving frontend route: 'css/226.c6b3ffe3.css'
[2025-06-09 13:47:26,544] INFO in __init__: Static folder: /app/aphrodite-web/frontend/dist
2025-06-09 13:47:26,544 - app - INFO - Static folder: /app/aphrodite-web/frontend/dist
2025-06-09 13:47:26,544 - app - INFO - Static folder: /app/aphrodite-web/frontend/dist
[2025-06-09 13:47:26,544] INFO in __init__: Static folder exists: True
2025-06-09 13:47:26,544 - app - INFO - Static folder exists: True
2025-06-09 13:47:26,544 - app - INFO - Static folder exists: True
[2025-06-09 13:47:26,545] INFO in __init__: Serving static file: css/226.c6b3ffe3.css
2025-06-09 13:47:26,545 - app - INFO - Serving static file: css/226.c6b3ffe3.css
[2025-06-09 13:47:26,548] INFO in __init__: Serving frontend route: 'js/226.54aaeb1f.js'
2025-06-09 13:47:26,545 - app - INFO - Serving static file: css/226.c6b3ffe3.css
2025-06-09 13:47:26,548 - app - INFO - Serving frontend route: 'js/226.54aaeb1f.js'
2025-06-09 13:47:26,548 - app - INFO - Serving frontend route: 'js/226.54aaeb1f.js'
[2025-06-09 13:47:26,551] INFO in __init__: Static folder: /app/aphrodite-web/frontend/dist
2025-06-09 13:47:26,551 - app - INFO - Static folder: /app/aphrodite-web/frontend/dist
2025-06-09 13:47:26,551 - app - INFO - Static folder: /app/aphrodite-web/frontend/dist
2025-06-09 13:47:26,552 - werkzeug - INFO - 10.0.15.8 - - [09/Jun/2025 13:47:26] "GET /css/226.c6b3ffe3.css HTTP/1.1" 304 -
[2025-06-09 13:47:26,553] INFO in __init__: Static folder exists: True
2025-06-09 13:47:26,553 - app - INFO - Static folder exists: True
2025-06-09 13:47:26,553 - app - INFO - Static folder exists: True
[2025-06-09 13:47:26,554] INFO in __init__: Serving static file: js/226.54aaeb1f.js
2025-06-09 13:47:26,554 - app - INFO - Serving static file: js/226.54aaeb1f.js
2025-06-09 13:47:26,554 - app - INFO - Serving static file: js/226.54aaeb1f.js
2025-06-09 13:47:26,557 - werkzeug - INFO - 10.0.15.8 - - [09/Jun/2025 13:47:26] "GET /js/226.54aaeb1f.js HTTP/1.1" 304 -
[2025-06-09 13:47:26,600] INFO in libraries: Attempting to load Jellyfin settings from database...
2025-06-09 13:47:26,600 - app.api.libraries - INFO - Attempting to load Jellyfin settings from database...
2025-06-09 13:47:26,600 - app.api.libraries - INFO - Attempting to load Jellyfin settings from database...
[2025-06-09 13:47:26,600] INFO in settings_service: DEBUG: Initializing database at /app/data/aphrodite.db
2025-06-09 13:47:26,600 - app.services.settings_service - INFO - DEBUG: Initializing database at /app/data/aphrodite.db
2025-06-09 13:47:26,600 - app.services.settings_service - INFO - DEBUG: Initializing database at /app/data/aphrodite.db
[2025-06-09 13:47:26,601] DEBUG in settings_service: DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-09 13:47:26,601 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-09 13:47:26,601 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
[2025-06-09 13:47:26,603] DEBUG in settings_service: DEBUG: Database connection successful
2025-06-09 13:47:26,603 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
2025-06-09 13:47:26,603 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
[2025-06-09 13:47:26,609] INFO in settings_service: DEBUG: Created/verified settings table
2025-06-09 13:47:26,609 - app.services.settings_service - INFO - DEBUG: Created/verified settings table
2025-06-09 13:47:26,609 - app.services.settings_service - INFO - DEBUG: Created/verified settings table
[2025-06-09 13:47:26,611] INFO in settings_service: DEBUG: Created/verified api_keys table
2025-06-09 13:47:26,611 - app.services.settings_service - INFO - DEBUG: Created/verified api_keys table
2025-06-09 13:47:26,611 - app.services.settings_service - INFO - DEBUG: Created/verified api_keys table
[2025-06-09 13:47:26,613] INFO in settings_service: DEBUG: Created/verified badge_settings table
2025-06-09 13:47:26,613 - app.services.settings_service - INFO - DEBUG: Created/verified badge_settings table
2025-06-09 13:47:26,613 - app.services.settings_service - INFO - DEBUG: Created/verified badge_settings table
[2025-06-09 13:47:26,615] INFO in settings_service: DEBUG: Created/verified settings_version table
2025-06-09 13:47:26,615 - app.services.settings_service - INFO - DEBUG: Created/verified settings_version table
2025-06-09 13:47:26,615 - app.services.settings_service - INFO - DEBUG: Created/verified settings_version table
[2025-06-09 13:47:26,617] INFO in settings_service: DEBUG: Created/verified app_version table
2025-06-09 13:47:26,617 - app.services.settings_service - INFO - DEBUG: Created/verified app_version table
2025-06-09 13:47:26,617 - app.services.settings_service - INFO - DEBUG: Created/verified app_version table
[2025-06-09 13:47:26,619] INFO in settings_service: DEBUG: Created/verified schedules table
2025-06-09 13:47:26,619 - app.services.settings_service - INFO - DEBUG: Created/verified schedules table
2025-06-09 13:47:26,619 - app.services.settings_service - INFO - DEBUG: Created/verified schedules table
[2025-06-09 13:47:26,621] INFO in settings_service: DEBUG: Created/verified schedule_processing_options table
2025-06-09 13:47:26,621 - app.services.settings_service - INFO - DEBUG: Created/verified schedule_processing_options table
2025-06-09 13:47:26,621 - app.services.settings_service - INFO - DEBUG: Created/verified schedule_processing_options table
[2025-06-09 13:47:26,623] INFO in settings_service: DEBUG: Created/verified schedule_target_directories table
2025-06-09 13:47:26,623 - app.services.settings_service - INFO - DEBUG: Created/verified schedule_target_directories table
2025-06-09 13:47:26,623 - app.services.settings_service - INFO - DEBUG: Created/verified schedule_target_directories table
[2025-06-09 13:47:26,625] INFO in settings_service: DEBUG: Created/verified job_history table
2025-06-09 13:47:26,625 - app.services.settings_service - INFO - DEBUG: Created/verified job_history table
2025-06-09 13:47:26,625 - app.services.settings_service - INFO - DEBUG: Created/verified job_history table
[2025-06-09 13:47:26,629] INFO in settings_service: DEBUG: Created/verified review_sources table
2025-06-09 13:47:26,629 - app.services.settings_service - INFO - DEBUG: Created/verified review_sources table
2025-06-09 13:47:26,629 - app.services.settings_service - INFO - DEBUG: Created/verified review_sources table
[2025-06-09 13:47:26,631] INFO in settings_service: DEBUG: Created/verified review_settings table
2025-06-09 13:47:26,631 - app.services.settings_service - INFO - DEBUG: Created/verified review_settings table
2025-06-09 13:47:26,631 - app.services.settings_service - INFO - DEBUG: Created/verified review_settings table
[2025-06-09 13:47:26,633] INFO in settings_service: DEBUG: Database initialization completed successfully
2025-06-09 13:47:26,633 - app.services.settings_service - INFO - DEBUG: Database initialization completed successfully
2025-06-09 13:47:26,633 - app.services.settings_service - INFO - DEBUG: Database initialization completed successfully
[2025-06-09 13:47:26,633] DEBUG in settings_service: DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-09 13:47:26,633 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-09 13:47:26,633 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
[2025-06-09 13:47:26,634] DEBUG in settings_service: DEBUG: Database connection successful
2025-06-09 13:47:26,634 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
2025-06-09 13:47:26,634 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
[2025-06-09 13:47:26,641] INFO in libraries: Successfully loaded Jellyfin settings from database: http://jellyfin:8096
2025-06-09 13:47:26,641 - app.api.libraries - INFO - Successfully loaded Jellyfin settings from database: http://jellyfin:8096
2025-06-09 13:47:26,641 - app.api.libraries - INFO - Successfully loaded Jellyfin settings from database: http://jellyfin:8096
2025-06-09 13:47:26,912 - werkzeug - INFO - 10.0.15.8 - - [09/Jun/2025 13:47:26] "GET /api/libraries/ HTTP/1.1" 200 -
[2025-06-09 13:47:29,375] INFO in library_routes: Loading Jellyfin settings from database for library 44e9e43b4061ccf7f51dc2c4f84e7afd...
2025-06-09 13:47:29,375 - app.api.poster_routes.library_routes - INFO - Loading Jellyfin settings from database for library 44e9e43b4061ccf7f51dc2c4f84e7afd...
2025-06-09 13:47:29,375 - app.api.poster_routes.library_routes - INFO - Loading Jellyfin settings from database for library 44e9e43b4061ccf7f51dc2c4f84e7afd...
[2025-06-09 13:47:29,375] INFO in settings_service: DEBUG: Initializing database at /app/data/aphrodite.db
2025-06-09 13:47:29,375 - app.services.settings_service - INFO - DEBUG: Initializing database at /app/data/aphrodite.db
2025-06-09 13:47:29,375 - app.services.settings_service - INFO - DEBUG: Initializing database at /app/data/aphrodite.db
[2025-06-09 13:47:29,376] DEBUG in settings_service: DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-09 13:47:29,376 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-09 13:47:29,376 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
[2025-06-09 13:47:29,376] DEBUG in settings_service: DEBUG: Database connection successful
2025-06-09 13:47:29,376 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
2025-06-09 13:47:29,376 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
[2025-06-09 13:47:29,381] INFO in settings_service: DEBUG: Created/verified settings table
2025-06-09 13:47:29,381 - app.services.settings_service - INFO - DEBUG: Created/verified settings table
2025-06-09 13:47:29,381 - app.services.settings_service - INFO - DEBUG: Created/verified settings table
[2025-06-09 13:47:29,383] INFO in settings_service: DEBUG: Created/verified api_keys table
2025-06-09 13:47:29,383 - app.services.settings_service - INFO - DEBUG: Created/verified api_keys table
2025-06-09 13:47:29,383 - app.services.settings_service - INFO - DEBUG: Created/verified api_keys table
[2025-06-09 13:47:29,385] INFO in settings_service: DEBUG: Created/verified badge_settings table
2025-06-09 13:47:29,385 - app.services.settings_service - INFO - DEBUG: Created/verified badge_settings table
2025-06-09 13:47:29,385 - app.services.settings_service - INFO - DEBUG: Created/verified badge_settings table
[2025-06-09 13:47:29,387] INFO in settings_service: DEBUG: Created/verified settings_version table
2025-06-09 13:47:29,387 - app.services.settings_service - INFO - DEBUG: Created/verified settings_version table
2025-06-09 13:47:29,387 - app.services.settings_service - INFO - DEBUG: Created/verified settings_version table
[2025-06-09 13:47:29,389] INFO in settings_service: DEBUG: Created/verified app_version table
2025-06-09 13:47:29,389 - app.services.settings_service - INFO - DEBUG: Created/verified app_version table
2025-06-09 13:47:29,389 - app.services.settings_service - INFO - DEBUG: Created/verified app_version table
[2025-06-09 13:47:29,391] INFO in settings_service: DEBUG: Created/verified schedules table
2025-06-09 13:47:29,391 - app.services.settings_service - INFO - DEBUG: Created/verified schedules table
2025-06-09 13:47:29,391 - app.services.settings_service - INFO - DEBUG: Created/verified schedules table
[2025-06-09 13:47:29,393] INFO in settings_service: DEBUG: Created/verified schedule_processing_options table
2025-06-09 13:47:29,393 - app.services.settings_service - INFO - DEBUG: Created/verified schedule_processing_options table
2025-06-09 13:47:29,393 - app.services.settings_service - INFO - DEBUG: Created/verified schedule_processing_options table
[2025-06-09 13:47:29,395] INFO in settings_service: DEBUG: Created/verified schedule_target_directories table
2025-06-09 13:47:29,395 - app.services.settings_service - INFO - DEBUG: Created/verified schedule_target_directories table
2025-06-09 13:47:29,395 - app.services.settings_service - INFO - DEBUG: Created/verified schedule_target_directories table
[2025-06-09 13:47:29,397] INFO in settings_service: DEBUG: Created/verified job_history table
2025-06-09 13:47:29,397 - app.services.settings_service - INFO - DEBUG: Created/verified job_history table
2025-06-09 13:47:29,397 - app.services.settings_service - INFO - DEBUG: Created/verified job_history table
[2025-06-09 13:47:29,398] INFO in settings_service: DEBUG: Created/verified review_sources table
2025-06-09 13:47:29,398 - app.services.settings_service - INFO - DEBUG: Created/verified review_sources table
2025-06-09 13:47:29,398 - app.services.settings_service - INFO - DEBUG: Created/verified review_sources table
[2025-06-09 13:47:29,400] INFO in settings_service: DEBUG: Created/verified review_settings table
2025-06-09 13:47:29,400 - app.services.settings_service - INFO - DEBUG: Created/verified review_settings table
2025-06-09 13:47:29,400 - app.services.settings_service - INFO - DEBUG: Created/verified review_settings table
[2025-06-09 13:47:29,403] INFO in settings_service: DEBUG: Database initialization completed successfully
2025-06-09 13:47:29,403 - app.services.settings_service - INFO - DEBUG: Database initialization completed successfully
2025-06-09 13:47:29,403 - app.services.settings_service - INFO - DEBUG: Database initialization completed successfully
[2025-06-09 13:47:29,403] DEBUG in settings_service: DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-09 13:47:29,403 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
2025-06-09 13:47:29,403 - app.services.settings_service - DEBUG - DEBUG: Connecting to database at /app/data/aphrodite.db
[2025-06-09 13:47:29,404] DEBUG in settings_service: DEBUG: Database connection successful
2025-06-09 13:47:29,404 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
2025-06-09 13:47:29,404 - app.services.settings_service - DEBUG - DEBUG: Database connection successful
[2025-06-09 13:47:29,410] INFO in library_routes: Successfully loaded Jellyfin settings from database: http://jellyfin:8096
2025-06-09 13:47:29,410 - app.api.poster_routes.library_routes - INFO - Successfully loaded Jellyfin settings from database: http://jellyfin:8096
2025-06-09 13:47:29,410 - app.api.poster_routes.library_routes - INFO - Successfully loaded Jellyfin settings from database: http://jellyfin:8096
2025-06-09 13:47:29,422 - werkzeug - INFO - 10.0.15.8 - - [09/Jun/2025 13:47:29] "GET /api/poster-manager/library/44e9e43b4061ccf7f51dc2c4f84e7afd HTTP/1.1" 200 -

```

**Comment by jackkerouac** [comment]
From looking at your logs, this could be a couple of things. But the most likely culprit is a network/proxy configuration issue.

Try:

1. Open Poster Manager page
2. Press F12 to open Developer Tools
3. Go to Network tab
4. Select a library and watch for failed requests
5. Look for 404/timeout errors on poster image requests
6. Note the exact URLs that are failing and report back

In your Settings page, try changing the Jellyfin URL field to either:

1. https://jellyfin.<reverse proxy hostname> (if using the same reverse proxy)
2. http://<server-ip>:8096 (if Jellyfin port is exposed)
3. whatever URL you use to access Jellyfin in their browser

If you are using a reverse proxy (nginx, traefik, Cloudflare Tunnel), and I assume you are from your logs, you may need to:

1. Add a proxy pass rule for Jellyfin Or configure Jellyfin to be accessible through the same reverse proxy
2. Update the Jellyfin URL in Aphrodite to use the external URL (see 6 above)

Once you update the Jellyfin URL in Aphrodite settings to use the externally accessible URL (same one you use in your browser), the poster images should load correctly instead of showing the default professor image.

If this is the problem (I think it might be, but I could be wrong), this is a common Docker networking issue where internal container hostnames aren't accessible from your browser. The fix is simple - just update the configuration to use the external URL.

Let me know if I got this correct - I could be talking out of my butt.

**Comment by mels0n** [comment]
> Once you update the Jellyfin URL in Aphrodite settings to use the externally accessible URL (same one you use in your browser), the poster images should load correctly instead of showing the default professor image.

Ok this is 100% the situation. 

- Aphrodite can reach Jellyfin through docker networking. 
- I setup connections to use the docker networking.
- My browser can not reach Jellyfin through the docker networking.
- I didn't realize the calls were going from browser to Jellyfin rather than from WebGUI through Aphrodite to Jellyfin.

You nailed it. I'll just use Jellyfin external url.

**Comment by jackkerouac** [comment]
Yay!
